### ISSUE TITLE
Create and implement Social Menu

### ISSUE THREAD

**Issue by listingslab** [listingslab-software/shared#4]
#### Mock Data

You can modify this data shape in any way you wish

`packages/shared/src/features/system/mock_data/social.tsx`

#### Guide

- Create new component called SocialMenu.tsx in 
`/packages/shared/src/components/social/`

- Get the data using appselector 
- Render the list as... well, as a list
- Popover menuify the component
- Hook it up to a redux thing

**Comment by DriveByAbuser** [comment]
ok
